# Generated by Django 3.2.3 on 2021-05-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carCode', models.CharField(max_length=9)),
                ('carModel', models.CharField(max_length=50)),
                ('manufacturingDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeCar', models.CharField(max_length=20)),
                ('typeEngine', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('F', 'Formula'), ('E', 'Endurance'), ('G', 'GT')], default='F', max_length=1)),
            ],
        ),
    ]
